/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/PZ4nArWSmt2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { DialogTitle, DialogDescription, DialogHeader, DialogContent, Dialog } from "@/components/ui/dialog"
import { Badge } from "@/components/ui/badge"
import Link from 'next/link'
import { Button } from "@/components/ui/button"

export function PlanUpgrade() {
  return (
    <Dialog defaultOpen>
      <DialogContent className="max-w-xl mx-auto">
        <DialogHeader>
          <DialogTitle>Billing</DialogTitle>
          <DialogDescription>
            Manage your billing and payment details. For any question, send us a mail at contact@volta.net.
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="border-b pb-4">
            <h3 className="text-lg font-semibold">Current plan</h3>
            <p className="text-sm text-muted-foreground">You are currently on the Free plan.</p>
          </div>
          <div className="border-b pb-4">
            <h3 className="text-lg font-semibold flex items-center">
              Upgrade to Pro
              <Badge className="ml-2" variant="secondary">
                14 days trial
              </Badge>
            </h3>
            <p className="text-sm text-muted-foreground">
              Get more out of Volta with advanced features for your organization.
            </p>
            <ul className="mt-4 space-y-2 text-sm">
              <li>✔ Roadmap planning</li>
              <li>✔ Group repositories in projects</li>
              <li>✔ Community leaderboard</li>
              <li>✔ Issues insights (soon)</li>
            </ul>
          </div>
          <div className="flex justify-between items-center pt-4">
            <div className="flex flex-col">
              <span className="text-lg font-semibold">€10</span>
              <span className="text-sm text-muted-foreground">per month plus local taxes</span>
            </div>
            <Link href="https://buy.stripe.com/test_8wM29JgeCc8GcKcfYY">Upgrade</Link>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
